[project]
name = "dlt-source-affinity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datamodel-code-generator>=0.26.4",
    "dlt>=1.4.1",
]

[tool.black]
include = '.*py$'
